name: Create ZIP and Release

on:
  push:
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create ZIP archive
      run: zip archive.zip a.txt

    - name: release name
      id: release_name
      run: |
        echo "tagname=$(echo $GITHUB_REF | sed 's|refs/tags/||')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.release_name.outputs.tagname }}
        release_name: Release ${{ steps.release_name.outputs.tagname }}
        draft: false
        prerelease: false

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./archive.zip
        asset_name: archive.zip
        asset_content_type: application/zip
